### ISSUE TITLE
Missing Keywords

### ISSUE THREAD

**Issue by callamaris** [mycelo1/vsc-oracle-plsql#1]
Hi,

vsc-oracle-plsql is the best syntax highlighter for plsql.

But here are some keywords missing:

  - AND, OR , NOT
  - XMLTYPE
  - Substitution variables & DEFINE
  - SQLPlus keywords
    (SIZE, SERVEROUTPUT, FORMAT, WRAPPED, ECHO, SPOOL, PROMPT, WHENEVER, SQLERROR, VERIFY ...)

**Comment by mycelo1** [comment]
- Boolean operators were intentionally left out for now.
- Maybe I cover Oracle's built-in types in the future.
- SQLPlus keywords often conflict with PLSQL's and will not be supported.
